#!/bin/bash
set -e

cd /home/userdepinfo/Documents/github/moon-apt-repo || exit 1
git checkout gh-pages
git pull origin gh-pages --allow-unrelated-histories
git add pool/main/b/bashrc-script-custom/*.deb
git add dists/*
git commit -m "deploy: bashrc-script-custom_${VERSION}_all.deb"
git push origin gh-pages